Locales['es'] = {

	['robbery_cancelled'] = 'El robo fue cancelado',
	['shop_robbery'] = 'Robo en joyeria',
	['press_to_rob'] = 'Dispara para iniciar el robo',
	['seconds_remaining'] = '~w~ segundos restantes',
	['robbery_cancelled_at'] = '~r~ el robo fue cancelado en: ~b~',
	['robbery_has_cancelled'] = '~r~ el robo fue cancelado: ~b~',
	['already_robbed'] = 'la joyeria fue robada. Espera: ',
	['seconds'] = 'segundos.',
	['rob_in_prog'] = '~r~ robo en progreso en: ~b~',
	['started_to_rob'] = 'Iniciaste el robo ',
	['do_not_move'] = ', Toma las joyas de las vitrinas!',
	['alarm_triggered'] = 'La alarma se activo',
	['hold_pos'] = 'cuando tu\'tengas las joyas sal corriendo!',
	['robbery_complete'] = '~r~ El robo fue un exito~s~ ~h~ Corre! ',
	['robbery_complete_at'] = '~r~ El robo fue completado en: ~b~',
	['min_two_police'] = 'Necesita haber minimo ~b~',
	['min_two_police2'] = ' ~w~Policias en la ciudad.',
	['robbery_already'] = '~r~otro robo esta en progreso.',
	['robbery_has_ended'] = 'Robo finalizado',
	['end'] = 'La joyeria fue robada',
	['notenoughgold'] = '~r~Seguramente no tienes suficientes joyas',
	['copsforsell'] = 'necesitan haber minimo ~b~',
	['copsforsell2'] = ' ~w~policias en la ciudad para vender',
	['goldsell'] = '~y~Joyas~s~ en proceso de venta',
	['field'] = 'Press ~y~E~s~ to ~o~collect~s~ las joyas',
	['collectinprogress'] = 'recoleccion en progreso...',
	['lester'] = '~g~Robaste la joyeria! ahora llevale las joyas a ~r~Lester!',
	['jewelsblipmap'] = 'Joyas',
	['press_to_collect'] = 'para recoger joyas',
	['smash_case'] = 'vitrinas rotas',
	['press_to_sell'] = 'Presiona ~INPUT_PICKUP~ para vender las joyas',
	['need_bag'] = 'Necesitas una bolsa comprala en la tienda de ropa!.'

}
